### ISSUE TITLE
TvOS port

### ISSUE THREAD

**Issue by FuzzyNutz** [vgmoose/nc-client#7]
Can someone port this to tvOS ?

**Comment by vgmoose** [comment]
Thanks for the suggestion, I've now added an initial tvOS port now in https://github.com/vgmoose/nc-client/commit/60b08a6c8e5c00d2a2253c1d8ab403ba61a2bfcf

Inputting on tvOS isn't very convenient, but most of the same code does seem to work:
![ezgif-3-c6dca61bd9](https://user-images.githubusercontent.com/2467473/34451741-14df22f6-ecfe-11e7-8015-349ee052d983.gif)
